### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by matthewlein** [ericwbailey/millennials-to-snake-people#15]
Hi, getting this logged in the console
`Uncaught SyntaxError: Invalid regular expression: /\bGeneration Z)\b/: Unmatched ')'`
v = v.replace(/\bGeneration Z)\b/g, "The Zolom's children");

Which you can see at the `Z)`.

Strangely, the source doesn't show that error, so maybe the chrome extension is not updated?

P.S. This extension is soo :100:, it brings me so much joy and really represents everything I love about the internet.

**Comment by ericwbailey** [comment]
Ah, thanks for posting! I caught this late last night and I think it's fixed now. What version of the extension do you currently have? I'm not seeing any complaints in the console for ver 1.6.1.

**Comment by matthewlein** [comment]
Yep, i had 1.6 and it didn't want to update I guess. Trashing and reinstalling got me 1.6.1 and no errors.
