### ISSUE TITLE
Feature request: Highlight icon when substitutions have been made

### ISSUE THREAD

**Issue by johnchristopherjones** [ericwbailey/millennials-to-snake-people#20]
I'd love to be able to look at the extension's icon and see a visual indication if a substitution has been made, so that I can confirm a substitution a substitution has been made if I'm confused about something I'm reading.

**Comment by ericwbailey** [comment]
Nice idea, but I don't think this sort of feature is really in keeping for what I'd like the experience of the plugin to be.
